-- SEG Vendas: estrutura mínima para a sincronização entre filiais.
-- Execute uma única vez no SQL Editor do Supabase.

create table if not exists public.seg_sync_events (
    sequence bigint generated by default as identity primary key,
    event_id text not null unique,
    origin_store_id text not null,
    entity text not null,
    operation text not null,
    payload jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    inserted_at timestamptz not null default now()
);

create index if not exists seg_sync_events_sequence_idx
    on public.seg_sync_events (sequence);
create index if not exists seg_sync_events_entity_idx
    on public.seg_sync_events (entity, operation);

-- O navegador não acessa este ledger. O servidor Python usa apenas a chave
-- secreta e o papel service_role, que ignora RLS sem expor dados ao público.
alter table public.seg_sync_events enable row level security;
revoke all on table public.seg_sync_events from anon, authenticated;
grant all on table public.seg_sync_events to service_role;
grant usage, select on sequence public.seg_sync_events_sequence_seq to service_role;

-- Reservada para a próxima etapa: dados compartilháveis (clientes, produtos,
-- preços, descrições e categorias). A chave é composta pela filial e pelo
-- documento para que cada loja mantenha seu backup local independente.
create table if not exists public.seg_sync_documents (
    store_id text not null,
    document_key text not null,
    payload jsonb not null default '{}'::jsonb,
    version bigint not null default 1,
    updated_at timestamptz not null default now(),
    primary key (store_id, document_key)
);

alter table public.seg_sync_documents enable row level security;
revoke all on table public.seg_sync_documents from anon, authenticated;
grant all on table public.seg_sync_documents to service_role;
